### PR TITLE
Doc: Remove Virtual

### PR DESCRIPTION
**Pull request by umut-sahin**

### CODE REVIEW

**Comment by aquint-zama** [comment]
maybe we could start a `UPGRADING.md` document with this feature removal to explain how to upgrade existing code (see CML https://github.com/zama-ai/concrete-ml-internal/issues/3042)

**Comment by umut-sahin** [comment]
I don't think it's a good idea to do in the official docs for a version. We can however include a guide to upgrade in release notes and announcement blog post.

**Comment by aquint-zama** [comment]
> I don't think it's a good idea to do in the official docs for a version. We can however include a guide to upgrade in release notes and announcement blog post.

not sure to get you right, I'm talking about a file named UPGRADING.md for this kind of upgrade notes, I added examples in the CML issue. I'm not talking about adding these info in the documentation.

**Comment by umut-sahin** [comment]
Oh I see, we could do that yes, or write a small guide for each release with breaking changes, as you wish.

**Review by aquint-zama — APPROVED** [review]

**Pull request merged**
